### ISSUE TITLE
Email subscription page jumps when it first loads

### ISSUE THREAD

**Issue by paustint** [legiblenews/community#17] opened 2022-11-10 01:25 UTC
**When the page first loads, this text is shown:**
You are subscribed to the daily edition of Legible News. The November 11 issue will be emailed to X tomorrow at 5:00pm.

**Immediately after, the text changes to:**
You are subscribed to the daily edition of Legible News. The Thursday issue will be emailed to X tomorrow at 5:00pm.

1. The page should be stable and should not change immediately after being loaded
2. Not sure where November 11 is coming from, current date/time: `Wed Nov 09 2022 18:24:06 GMT-0700 (Mountain Standard Time)` Thursday (tomorrow) is November 10, not November 11

**Comment by bradgessler** [comment] 2023-10-19 20:57
Thanks for reporting! This is working as designed (which isn't ideal) because it loads UTC, then the JS kicks in after the page loads and adjust the time to your local offset. The alternative is I block the loading of the page to apply the TZ, which would slow things down.

I don't have any plans on fixing this unless this library gets updated. For now I'll close this issue and hope  a future `bundle update` fixes it.

**Closed as completed by bradgessler** 2023-10-19 20:57 UTC
